### PR TITLE
fixed syntax for multi-node

### PR DESCRIPTION
**Pull request by pgalonza**
Signed-off-by: Galonza Peter <p.galonza@evaron.ru>

### Description
This changes fixed mistake in opensearch.yml(opensearch-multi-node.yml) "IllegalStateException[only value lists are allowed in serialized settings]"

Check List
[X ] Commits are signed per the DCO using --signoff
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check here.

### CODE REVIEW

**Comment by saravanan30erd** [comment]
@pgalonza  Could you please explain when you faced the below issue?  what is the value which provides this error?

```IllegalStateException[only value lists are allowed in serialized settings]```

Current setting with `[]` is working fine and its explicitly mentioned based on below doc,

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.htmlhttps://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html

**Comment by pgalonza** [comment]
> @pgalonza Could you please explain when you faced the below issue? what is the value which provides this error?
> 
> `IllegalStateException[only value lists are allowed in serialized settings]`
> 
> Current setting with `[]` is working fine and its explicitly mentioned based on below doc,
> 
> https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.htmlhttps://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html

@saravanan30erd I faced this problem when checked usual installation on 3 VMs with centos8. When open opensearch configuration file i saw this `node.roles: [['ingest', 'data']]`, because `{{ hostvars[inventory_hostname]['roles'] }}` return the list with correct syntax, i think it is usual type conversion the list to string.

Tested on:
- Python 3.10.0
- Ansible 3.0.5, 4.10.0, 5.0

Screenshots:
[https://disk.yandex.ru/i/9lj058BYoPe-ZQ](url)
[https://disk.yandex.ru/i/JBWsGZQcsf5k9A](url)

**Comment by saravanan30erd** [comment]
@pgalonza ok, when I was tested with python 2.7 and python 3.6 this is not the case and thats why I explicitly mentioned list in config file. Currently we are working on support for Amazon linux & ubuntu PR's. Once thats merged, then we will look into this issue bcoz this requires some more time as it needs to be tested against different versions of python & ansible to reproduce the issue, also we need to check for backward compatibility.

**Comment by pgalonza** [comment]
I`m tested with inventory in yaml format and attribute was be a list not a string

**Pull request closed without merging**
