### PR TITLE
Add Saravanan30erd as the new community maintainer

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Add Saravanan30erd as the new community maintainer
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by CEHENKLE — APPROVED** [review]
Yay @saravanan30erd !

**Comment by peterzhuamazon** [comment]
Once this PR is merged we will attempt to add you in the org on github, before assigning the maintainer access.
This would take some time please be patient.

Thanks.

**Review by bbarani — APPROVED** [review]

**Comment by bbarani** [comment]
Welcome @saravanan30erd !

**Comment by peterzhuamazon** [comment]
Hi @saravanan30erd we have sent out the invite, please accept, thanks.

**Comment by saravanan30erd** [comment]
Thanks Guys. Happy to be part of this community.

**Pull request merged**
