### PR TITLE
separate dashboards version

### LINKED ISSUE #18: [Enhancement]Need to separate OpenSearch vs Dashboards version in Ansible Playbook
**Is your feature request related to a problem? Please describe.**
It is possible that a OpenSearch and Dashboards binaries having different version.
Ex: 1.1.1 Dashboards can still use for OpenSearch 1.1.0.

As of now it seems their versions are controlled by a single version number.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by saravanan30erd**
### Issues Resolved
#18 
 
### Check List
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by saravanan30erd** [comment]
@peterzhuamazon please review

**Review by peterzhuamazon — APPROVED** [review]
Thanks.

**Review by peternied — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Hi @saravanan30erd due to #23 can you change OpenSearch to use 1.2.1, while dashboards stays on 1.2.0 version.

Thanks.

**Comment by saravanan30erd** [comment]
@peterzhuamazon  Done

**Comment by peterzhuamazon** [comment]
Thanks @saravanan30erd

**Pull request merged**
