### PR TITLE
korkin25 fixed/features

### PR DESCRIPTION
**Pull request by korkin25**
### Description

- Vargantfile for full stack testing
- maximum avoiding root operations
- "# vim:ft=ansible:"
- host_download: ability to download artifacts on ansible controller. remotes can in closed segment w/o inet. Also it can help with slow internet connection

I will continue my work specified regarding following:

- configurable optional ufw support
- configurable optional logstash integration
- misc usability features
- fluebtbit config examples

### Issues Resolved

- security fixes to minimize root operations

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @korkin25 thanks for the contribution.

We are currently a bit busy with release so it might take some time for this PR to get reviewed and merged.

@saravanan30erd @rodolfovillordo @prudhvigodithi would you mind take a look when you have time?

@korkin25 you also need to sign DCO on your commits.

Thanks.

**Comment by prudhvigodithi** [comment]
Hey @korkin25 thanks for your patience, I did notice there are some conflicts to the PR, can you please take a look?

**Comment by prudhvigodithi** [comment]
Also can you please create a related issue to this PR and add some details to the issue on why this PR is raised?
Thank you 
@bbarani @peterzhuamazon @saravanan30erd

**Comment by dblock** [comment]
Closing as stalled, feel free to finish and reopen @korkin25.

[Catch All Triage, attendees [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/lukas-vlcek/), [4](https://github.com/rafaelma), [5](https://github.com/krisfreedain), [6](https://github.com/gargrajat), [7](https://github.com/andrross)]

**Pull request closed without merging**
