### PR TITLE
Creating ISM polisies via role

### PR DESCRIPTION
**Pull request by ssi444**
### Description
Added the ability to automatically create ISM policies.

### Issues Resolved
https://github.com/opensearch-project/ansible-playbook/issues/66

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ssi444** [comment]
@peterzhuamazon @saravanan30erd @prudhvigodithi ping

**Comment by ssi444** [comment]
@peterzhuamazon @saravanan30erd @prudhvigodithi ping

**Comment by prudhvigodithi** [comment]
Hey @ssi444 apologies for the delay, do you think we still need this change to move forward?

**Comment by prudhvigodithi** [comment]
Hey @ssi444 apologies for the delay, do you think we still need this change to move forward?

**Comment by ssi444** [comment]
> Hey @ssi444 apologies for the delay, do you think we still need this change to move forward?

This is one of the important tasks for using this role as an IaS.  In production, we most often add ISM and index pattern (PR #68)

**Comment by peterzhuamazon** [comment]
> Thanks @ssi444, @peterzhuamazon please add your thoughts on this PR and index pattern (PR #68) Thank you

Hi all,

We welcome the contribution but it looks like doesn't cater to wider variety of users as it specifically add settings for a plugin or two.

Need more discussion on whether this is addition to the repo, or is just support for user-specific scenario.
Let me know what you guys think @bbarani @gaiksaya @rishabh6788 .

Thanks.

**Comment by ssi444** [comment]
If the number of users using this role for regular cluster updates according to the IaC methodology is insignificant, then it may not be worth implementing this PR. We are actively using this in production and I decided to share our best practices with the community. With this role we manage:
- index pattern
- ISM
- installing plugins

There are plans to complete the management of visualizations and dashboards. We don't use them at home, but if the community is interested, then I can make the necessary improvements.

**Comment by bbarani** [comment]
Anyone looking in to this PR?  @prudhvigodithi @peterzhuamazon @TheAlgo

**Comment by dblock** [comment]
Looks like there was no consensus of what to do with this PR. Closing it as stalled, please reopen if you don't agree!

[Catch All Triage - Attendees [1](https://github.com/dblock/), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/gkamat), [5](https://github.com/getsaurabh02)]

**Pull request closed without merging**
