### PR TITLE
Fix a couple of ansible-lint errors

### PR DESCRIPTION
**Pull request by mpsOxygen**
### Description
Fixes a couple of ansible-lint errors

### Issues Resolved
Cosmetic changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by mpsOxygen** [comment]
> Hey @mpsOxygen, thanks for the contribution, can you please fix the DCO? Thank you

Fixed.

**Comment by prudhvigodithi** [comment]
Hey @mpsOxygen by default Ansible infers the modules and plugins contained in ansible-core, so should we still use as `Ansible.Builtin`?
@peterzhuamazon

**Comment by peterzhuamazon** [comment]
> Hey @mpsOxygen by default Ansible infers the modules and plugins contained in ansible-core, so should we still use as `Ansible.Builtin`? @peterzhuamazon

I think it is just to be clear it is buildin?
So the linting will not warn?
Think we should add a linter at this point, per my issue #58 on this repo.

**Comment by mpsOxygen** [comment]
> Hey @mpsOxygen by default Ansible infers the modules and plugins contained in ansible-core, so should we still use as `Ansible.Builtin`? @peterzhuamazon

Linting asks for it and it is a best practice in case there are modules with the same name but different namespace.

**Comment by peterzhuamazon** [comment]
Hi @mpsOxygen 
We recently merged another PR and yours now have some conflicts, sorry about it.
Could you kindly fix those conflicts?

Also @saravanan30erd @prudhvigodithi I am ok with this changes, let me know your thought here.
I think this is a good opportunity for us to introduce a linter workflow after this PR is merged.

Thanks

**Comment by mpsOxygen** [comment]
Ive changed the conflicting lines from pause module to wait_for module and also formatted it to be in yaml format instead of ini format (ini format is inline with = instead of :).

`- name: Wait for opensearch to startup
<<<<<<< main
  ansible.builtin.wait_for:
    host: {{ hostvars[inventory_hostname]['ip'] }}
    port: {{os_api_port}}
    delay: 5
    connect_timeout: 1
    timeout: 120
=======
  ansible.builtin.wait_for: host={{ hostvars[inventory_hostname]['ip'] }} port={{os_api_port}} delay=5 connect_timeout=1 timeout=120


>>>>>>> main`

**Comment by peterzhuamazon** [comment]
Hi @saravanan30erd @prudhvigodithi could you have you thoughts on this?
So we can move ahead with the changes.
Thanks.

**Comment by saravanan30erd** [comment]
@peterzhuamazon It looks fine to me. Ansible recommends to use builtin for easy linking to the module documentation and to avoid conflicting with other collections that may have the same module name.

**Comment by prudhvigodithi** [comment]
Hey @mpsOxygen can you please fix the conflicts and we can merge this PR?

**Comment by mpsOxygen** [comment]
> Hey @mpsOxygen can you please fix the conflicts and we can merge this PR?

The conflict is fixed in my opinion, it's just a difference in formating from ini format to yaml format.

**Comment by prudhvigodithi** [comment]
The Github reports as `This branch has conflicts that must be resolved`, please check @mpsOxygen 
Screenshot 2023-04-07 at 8 19 13 AM

**Comment by mpsOxygen** [comment]
> The Github reports as `This branch has conflicts that must be resolved`, please check @mpsOxygen Screenshot 2023-04-07 at 8 19 13 AM

I have checked and the conflict is just a difference in formatting:
```
- name: Wait for opensearch to startup
<<<<<<< main
  ansible.builtin.wait_for:
    host: "{{ hostvars[inventory_hostname]['ip'] }}"
    port: "{{ os_api_port }}"
    delay: 5
    connect_timeout: 1
    timeout: 120
=======
  ansible.builtin.wait_for: host={{ hostvars[inventory_hostname]['ip'] }} port={{os_api_port}} delay=5 connect_timeout=1 timeout=120


>>>>>>> main
```

**Comment by saravanan30erd** [comment]
@mpsOxygen we cannot merge this PR unless this conflict is resolved. Please do `git rebase` and resolve the conflicts.
Refer: https://docs.github.com/en/get-started/using-git/resolving-merge-conflicts-after-a-git-rebase

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Thanks @saravanan30erd @peterzhuamazon can you please add your approval?
Thank you

**Review by saravanan30erd — APPROVED** [review]

**Pull request merged**
